site_name: SyncTodoist Docs
theme:
    name: material
    features:
        - navigation.sections
        - content.code.annotate
    font: false

plugins:
    -   mkdocstrings:
            handlers:
                python:
                    options:
                        show_root_toc_entry: false
                        show_source: false
                        heading_level: 3
                        filters: [ "!Config" ]
                        merge_init_into_class: true
nav:
    -   Welcome: index.md
    -   Tutorials:
            -   Prerequisites: tutorials/prereqs.md
            -   Getting Started: tutorials/getting-started.md
    -   How-To Guides:
            -   Settings & Configuration: how-tos/settings.md
            -   Convenience Methods: how-tos/convenience-methods.md
    -   Reference:
            -   Overview: reference/index.md
            -   TodoistAPI: reference/todoist_api.md
            -   Managers: reference/managers.md
            -   Models: reference/models.md
            -   Exceptions: reference/exceptions.md
    -   Explanations: explanations/index.md

extra:
    consent:
        title: Cookie consent
        description: >-
            We don't use any cookies at all. We don't track you, we don't analyze your behavior. We just want to make sure
            that the information we give you here is useful. That's all.
    social:
        -   icon: fontawesome/brands/github
            link: https://github.com/gaborschulz
        -   icon: fontawesome/brands/linkedin
            link: https://gabor.link/edin
        -   icon: fontawesome/brands/mastodon
            link: https://fosstodon.org/@gaborschulz
    generator: false

copyright: >
    Copyright &copy; 2022 Gabor Schulz – <a href="#__consent">Change cookie settings</a> | 
    <a href="https://gaborschulz.com/imprint/index.html" target="_blank">Imprint</a> |
    <a href="https://www.iubenda.com/privacy-policy/8008630" target="_blank">Privacy Policy</a>

repo_url: https://github.com/gaborschulz/synctodoist

watch:
    - mkdocs.yml
    - docs
    - synctodoist

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_css:
    - https://cdn.gaborschulz.com/fonts/roboto/font.css
    - https://cdn.gaborschulz.com/fonts/roboto-mono/font.css
    - stylesheets/extra.css