site_name: SyncTodoist Docs
theme:
    name: material

plugins:
    -   mkdocstrings:
            handlers:
                python:
                    options:
                        show_root_toc_entry: false
                        show_source: false
                        heading_level: 3
                        filters: [ "!Config" ]
nav:
    -   Welcome: index.md
    -   Tutorial: tutorials/index.md
    -   How-To Guide: how-tos/index.md
    -   Reference:
            -   Overview: reference/index.md
            -   TodoistAPI: reference/todoist_api.md
            -   Managers: reference/managers.md
            -   Models: reference/models.md
            -   Exceptions: reference/exceptions.md
    -   Explanation: explanation/index.md

extra:
    consent:
        title: Cookie consent
        description: >-
            This site does not use any cookies whatsoever. No tracking, no personal data collection, only plain documentation.

copyright: >
    Copyright &copy; 2022 Gabor Schulz – <a href="#__consent">Change cookie settings</a>